### PR TITLE
feat: include reverted seq's in mutation candidate pool

### PR DESCRIPTION
**Pull request by 0xalpharush**

### CODE REVIEW

**Comment by 0xalpharush** [comment]
I believe you and @ggrieco-tob were discussing this, @aviggiano. Would you like to give it a spin and let use know if you see better results

**Comment by aviggiano** [comment]
I might be wrong, but I remember @anishnaik saying Echidna would not use reverted tx all the time, only very now and then. Shouldn't medusa do the same thing? or maybe have a config parameter %

**Comment by 0xalpharush** [comment]
@aviggiano Definitely worth fine-tuning this but I figured it was worth having a branch to try it out sooner than later. When we actually get ready to merge this we will also want to implement this as well https://github.com/crytic/echidna/issues/1264

**Comment by 0xalpharush** [comment]
https://github.com/crytic/medusa/pull/456 supersedes this

**Pull request closed without merging**
